config-version = "2.7"
bind = "0.0.0.0:25565"
motd = "${CFG_MOTD}"
show-max-players = ${CFG_MAX_PLAYERS}
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = false
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
announce-forge = false
kick-existing-players = false
ping-passthrough = "DISABLED"
enable-player-address-logging = true

[servers]
lobby = "lobby:25565"
survival = "survival:25565"

try = [
  "lobby"
]

[forced-hosts]

[advanced]
compression-threshold = 256
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
log-command-executions = false
log-player-connections = true
announce-proxy-commands = true
failover-on-unexpected-server-disconnect = true

[query]
enabled = false
port = 25565
map = "Modern Network"
show-plugins = false
